install R for MSstats
mwalzer/dockerfiles pull request #2
Opened 2018-10-26 14:10 UTC by timosachsenberg

2018-10-26 14:30 UTC, timosachsenberg commented
works fine on my PC with R 3.5 and the current bioconductor version.
Maybe we need to fix that to a known version so scripts don't break if bioconductor / Msstats is update?

2018-10-29 10:11 UTC, mwalzer commented
That is probably a good idea. Do you think the PPA is necessary?

Would this work, too?
```
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
add-apt-repository 'deb [arch=amd64,i386] https://cran.rstudio.com/bin/linux/ubuntu xenial/'
apt-get update
```

2018-10-29 10:56 UTC, timosachsenberg commented
Hmm I don’t know if this allows to choose a specific r version. I would like to fix it to 3.5 and a specific bioconductor Version as an update might break the msstats package

2018-10-29 11:18 UTC, mwalzer commented
Yes, I agree that it is a good idea to fix the versions. Do you know how to fix versions for bioclite installations?

2018-10-29 12:18 UTC, mwalzer requested changes
I really like the R integration, just added suggestions how to use the official cran repo (see here: https://cran.r-project.org/bin/linux/ubuntu/)

2018-10-29 12:18 UTC, mwalzer commented on batteries-included/Dockerfile
> +RUN apt-get install -y software-properties-common
```suggestion
RUN apt-get install -y software-properties-common apt-transport-https
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
RUN add-apt-repository 'deb [arch=amd64,i386] https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/'
RUN apt-get update
RUN apt install -y r-base
```

2018-10-29 12:18 UTC, mwalzer commented on batteries-included/Dockerfile
> +RUN add-apt-repository -y ppa:marutter/c2d4u3.5
```suggestion

```

2018-10-29 12:18 UTC, mwalzer commented on batteries-included/Dockerfile
> +RUN apt-get update
```suggestion

```

2018-10-29 12:18 UTC, mwalzer commented on batteries-included/Dockerfile
> +RUN apt install -y r-api-3.5
```suggestion

```

2018-10-29 13:09 UTC, mwalzer approved these changes

2018-10-29 13:09 UTC, merged